services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    networks:
      - gluetun_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/seth/docker/lidarr/data:/config
      - /mnt/hdd1/data/data:/data
    ports:
      - 8686:8686
    restart: unless-stopped
networks:
  gluetun_network:
    name: gluetun_network
    external: true
